CREATE ALGORITHM=UNDEFINED DEFINER=`conestoga`@`%` SQL SECURITY DEFINER VIEW `rvpark`.`customer_view` AS select `p`.`ID` AS `id`,`p`.`firstName` AS `firstName`,`p`.`lastName` AS `lastName`,concat(`p`.`firstName`,' ',`p`.`lastName`) AS `fullName`,`p`.`mainPhone` AS `mainPhone`,`p`.`email` AS `email`,`p`.`password` AS `password`,`c`.`cellPhone` AS `cellPhone`,`c`.`homePhone` AS `homePhone`,`c`.`faxNumber` AS `faxNumber`,`c`.`comments` AS `comments`,`c`.`street` AS `street`,`c`.`city` AS `city`,`c`.`postalCode` AS `postalCode`,`rvpark`.`countrycode`.`code` AS `countryCode`,`rvpark`.`countrycode`.`name` AS `countryName`,`rvpark`.`provincecode`.`code` AS `provinceCode`,`rvpark`.`provincecode`.`name` AS `provinceName`,`c`.`isEmailReceipt` AS `isEmailReceipt`,`c`.`isPartyMember` AS `isPartyMember` from (((`rvpark`.`customer` `c` join `rvpark`.`person` `p` on((`c`.`ID` = `p`.`ID`))) join `rvpark`.`provincecode` on((`c`.`provinceCode` = `rvpark`.`provincecode`.`code`))) join `rvpark`.`countrycode` on((`c`.`countryCode` = `rvpark`.`countrycode`.`code`)));

CREATE ALGORITHM=UNDEFINED DEFINER=`conestoga`@`%` SQL SECURITY DEFINER VIEW `rvpark`.`partymember_view` AS select `p`.`ID` AS `id`,`p`.`firstName` AS `firstName`,`p`.`lastName` AS `lastName`,concat(`p`.`firstName`,' ',`p`.`lastName`) AS `fullName`,`p`.`mainPhone` AS `mainPhone`,`p`.`email` AS `email`,`c`.`cellPhone` AS `cellPhone`,`c`.`petDescription` AS `petDescription`,`c`.`comments` AS `comments` from (`rvpark`.`partymember` `c` join `rvpark`.`person` `p` on((`c`.`ID` = `p`.`ID`)));

CREATE ALGORITHM=UNDEFINED DEFINER=`conestoga`@`%` SQL SECURITY DEFINER VIEW `rvpark`.`payment_view` AS select `p`.`ID` AS `id`,`p`.`selectionTotal` AS `selectionTotal`,`p`.`amount` AS `amount`,`p`.`balance` AS `balance`,`p`.`createDate` AS `createDate`,`rfp`.`description` AS `reasonforpayment`,concat(`ie`.`year`,' ',group_concat(`pim`.`site` separator ', ')) AS `sites`,coalesce(`c`.`id`,-(1)) AS `idCustomer`,`c`.`fullName` AS `fullName`,`c`.`mainPhone` AS `mainPhone` from ((((((`rvpark`.`payment` `p` left join `rvpark`.`paymentreservationitem` `pri` on((`p`.`ID` = `pri`.`idPayment`))) left join `rvpark`.`reservationitem` `ri` on((`pri`.`idReservationItem` = `ri`.`ID`))) left join `rvpark`.`placeinmap` `pim` on((`ri`.`idRVSite` = `pim`.`ID`))) left join `rvpark`.`customer_view` `c` on((`p`.`idCustomer` = `c`.`id`))) left join `rvpark`.`reasonforpayment` `rfp` on((`p`.`idReasonForPayment` = `rfp`.`ID`))) left join `rvpark`.`ipmevent` `ie` on((`pim`.`idIPMEvent` = `ie`.`ID`))) group by `p`.`ID`;

CREATE ALGORITHM=UNDEFINED DEFINER=`conestoga`@`%` SQL SECURITY DEFINER VIEW `rvpark`.`province_view` AS select `p`.`code` AS `provinceCode`,`p`.`name` AS `provinceName`,`p`.`countryCode` AS `countryCode`,`c`.`name` AS `countryName` from (`rvpark`.`provincecode` `p` join `rvpark`.`countrycode` `c` on((`p`.`countryCode` = `c`.`code`)));

CREATE ALGORITHM=UNDEFINED DEFINER=`conestoga`@`%` SQL SECURITY DEFINER VIEW `rvpark`.`reservationitem_final_view` AS select `ri`.`ID` AS `ID`,`ri`.`idIPMEvent` AS `idIPMEvent`,`ri`.`idRVSite` AS `idRVSite`,`ri`.`idCustomer` AS `idCustomer`,`ri`.`idStaff` AS `idStaff`,`ri`.`checkInDate` AS `checkInDate`,`ri`.`checkOutDate` AS `checkOutDate`,`ri`.`site` AS `site`,`ri`.`siteType` AS `siteType`,`ri`.`duration` AS `duration`,`ri`.`weeks` AS `weeks`,`ri`.`days` AS `days`,`ri`.`weeklyRate` AS `weeklyRate`,`ri`.`dailyRate` AS `dailyRate`,`ri`.`amount` AS `amount`,`ri`.`additionalServicesDescription` AS `additionalServicesDescription`,`ri`.`additionalServicesAmount` AS `additionalServicesAmount`,`ri`.`total` AS `total`,`ri`.`numberMemberInParty` AS `numberMemberInParty`,`ri`.`isCancelled` AS `isCancelled`,`ri`.`comments` AS `comments`,`ri`.`createDate` AS `createDate`,`ri`.`lastUpdate` AS `lastUpdate`,`ri`.`timeStamp` AS `timeStamp` from (`rvpark`.`reservationitem` `ri` join `rvpark`.`reservationitem_newer_only` `o` on((`ri`.`ID` = `o`.`ID`)));

CREATE ALGORITHM=UNDEFINED DEFINER=`conestoga`@`%` SQL SECURITY DEFINER VIEW `rvpark`.`reservationitem_newer_only` AS select max(`rvpark`.`reservationitem`.`ID`) AS `ID` from `rvpark`.`reservationitem` group by `rvpark`.`reservationitem`.`idRVSite`;

CREATE ALGORITHM=UNDEFINED DEFINER=`conestoga`@`%` SQL SECURITY DEFINER VIEW `rvpark`.`rvsite_available_view` AS select `p`.`ID` AS `id`,`p`.`site` AS `RVSite`,`p`.`idIPMEvent` AS `idIPMEvent` from (((`rvpark`.`placeinmap` `p` left join `rvpark`.`selecteditem_final_view` `si` on((`si`.`idRVSite` = `p`.`ID`))) left join `rvpark`.`reservationitem_final_view` `ri` on((`ri`.`idRVSite` = `p`.`ID`))) left join `rvpark`.`outofserviceitem` `oi` on((`oi`.`idRVSite` = `p`.`ID`))) where ((`p`.`isRVSite` = 1) and (isnull(`si`.`idRVSite`) or (not(`si`.`isSiteChecked`))) and (isnull(`ri`.`idRVSite`) or `ri`.`isCancelled`) and isnull(`oi`.`idRVSite`));

CREATE ALGORITHM=UNDEFINED DEFINER=`conestoga`@`%` SQL SECURITY DEFINER VIEW `rvpark`.`rvsite_coord_view` AS select `p`.`ID` AS `id`,`c`.`seqCoordinate` AS `seq`,`e`.`year` AS `Year`,`p`.`site` AS `RVSite`,`c`.`longitude` AS `longitude`,`c`.`latitude` AS `latitude` from (((`rvpark`.`coordinates` `c` join `rvpark`.`placeinmap` `p` on((`c`.`idPlaceInMap` = `p`.`ID`))) join `rvpark`.`sitetype` `s` on((`p`.`idSiteType` = `s`.`ID`))) join `rvpark`.`ipmevent` `e` on((`p`.`idIPMEvent` = `e`.`ID`))) where (`p`.`isRVSite` = 1);

CREATE ALGORITHM=UNDEFINED DEFINER=`conestoga`@`%` SQL SECURITY DEFINER VIEW `rvpark`.`rvsite_status_view` AS select `p`.`ID` AS `id`,`e`.`year` AS `Year`,`p`.`site` AS `RVSite`,`z`.`description` AS `SiteSize`,`a`.`description` AS `PowerSupply`,`u`.`backgroundColor` AS `backgroundColor`,((isnull(`si`.`idRVSite`) or (not(`si`.`isSiteChecked`))) and (isnull(`ri`.`idRVSite`) or `ri`.`isCancelled`) and isnull(`oi`.`idRVSite`)) AS `isAvaialable`,`si`.`checkInDate` AS `SelectedFrom`,`si`.`checkOutDate` AS `SelectedUntil`,`ri`.`checkInDate` AS `ReservedFrom`,`ri`.`checkOutDate` AS `ReservedUntil`,`oi`.`startDate` AS `OutOfServiceFrom`,`oi`.`endDate` AS `OutOfServiceUntil`,`cv`.`fullName` AS `fullName`,`cv`.`mainPhone` AS `mainPhone` from (((((((((`rvpark`.`placeinmap` `p` join `rvpark`.`sitetype` `s` on((`p`.`idSiteType` = `s`.`ID`))) join `rvpark`.`styleurl` `u` on((`u`.`ID` = `s`.`idStyleUrl`))) join `rvpark`.`ipmevent` `e` on((`p`.`idIPMEvent` = `e`.`ID`))) join `rvpark`.`sitesize` `z` on((`s`.`idSiteSize` = `z`.`ID`))) join `rvpark`.`service` `a` on((`s`.`idService` = `a`.`ID`))) left join `rvpark`.`selecteditem_final_view` `si` on((`si`.`idRVSite` = `p`.`ID`))) left join `rvpark`.`reservationitem_final_view` `ri` on((`ri`.`idRVSite` = `p`.`ID`))) left join `rvpark`.`outofserviceitem` `oi` on((`oi`.`idRVSite` = `p`.`ID`))) left join `rvpark`.`customer_view` `cv` on((`ri`.`idCustomer` = `cv`.`id`))) where (`p`.`isRVSite` = 1);

CREATE ALGORITHM=UNDEFINED DEFINER=`conestoga`@`%` SQL SECURITY DEFINER VIEW `rvpark`.`selecteditem_final_view` AS select `si`.`ID` AS `ID`,`si`.`idSession` AS `idSession`,`si`.`idIPMEvent` AS `idIPMEvent`,`si`.`idRVSite` AS `idRVSite`,`si`.`idCustomer` AS `idCustomer`,`si`.`idStaff` AS `idStaff`,`si`.`isSiteChecked` AS `isSiteChecked`,`si`.`checkInDate` AS `checkInDate`,`si`.`checkOutDate` AS `checkOutDate`,`si`.`site` AS `site`,`si`.`siteType` AS `siteType`,`si`.`duration` AS `duration`,`si`.`weeks` AS `weeks`,`si`.`days` AS `days`,`si`.`weeklyRate` AS `weeklyRate`,`si`.`dailyRate` AS `dailyRate`,`si`.`amount` AS `amount`,`si`.`additionalServicesDescription` AS `additionalServicesDescription`,`si`.`additionalServicesAmount` AS `additionalServicesAmount`,`si`.`total` AS `total`,`si`.`idReservationItem` AS `idReservationItem`,`si`.`reservationCheckInDate` AS `reservationCheckInDate`,`si`.`reservationCheckOutDate` AS `reservationCheckOutDate`,`si`.`reservationAmount` AS `reservationAmount`,`si`.`reservationAdditionalServDescr` AS `reservationAdditionalServDescr`,`si`.`reservationAdditionalServAmount` AS `reservationAdditionalServAmount`,`si`.`createDate` AS `createDate`,`si`.`lastUpdate` AS `lastUpdate`,`si`.`timeStamp` AS `timeStamp` from (`rvpark`.`selecteditem` `si` join `rvpark`.`selecteditem_newer_only` `o` on((`si`.`ID` = `o`.`ID`)));

CREATE ALGORITHM=UNDEFINED DEFINER=`conestoga`@`%` SQL SECURITY DEFINER VIEW `rvpark`.`selecteditem_newer_only` AS select max(`rvpark`.`selecteditem`.`ID`) AS `ID` from `rvpark`.`selecteditem` group by `rvpark`.`selecteditem`.`idRVSite`;

CREATE ALGORITHM=UNDEFINED DEFINER=`conestoga`@`%` SQL SECURITY DEFINER VIEW `rvpark`.`site_description_rate_view` AS select `p`.`ID` AS `id`,`p`.`idIPMEvent` AS `idIPMEvent`,`p`.`site` AS `RVSite`,`p`.`idSiteType` AS `idSiteType`,concat(`size`.`description`,' ',`rvpark`.`service`.`description`) AS `description`,coalesce(`dayrate`.`rate`,0) AS `dailyRate`,coalesce(`weekrate`.`rate`,0) AS `weeklyRate` from (((((`rvpark`.`placeinmap` `p` join `rvpark`.`sitetype` `t` on(((`p`.`idSiteType` = `t`.`ID`) and (`p`.`isRVSite` = 1)))) left join `rvpark`.`sitesize` `size` on((`t`.`idSiteSize` = `size`.`ID`))) left join `rvpark`.`service` on((`t`.`idService` = `rvpark`.`service`.`ID`))) left join `rvpark`.`siterate` `dayrate` on(((`dayrate`.`idSiteType` = `t`.`ID`) and (`dayrate`.`period` = 'Daily')))) left join `rvpark`.`siterate` `weekrate` on(((`weekrate`.`idSiteType` = `t`.`ID`) and (`weekrate`.`period` = 'Weekly'))));

CREATE ALGORITHM=UNDEFINED DEFINER=`conestoga`@`%` SQL SECURITY DEFINER VIEW `rvpark`.`sitetype_service_rate_view` AS select `t`.`idIPMEvent` AS `eventId`,`t`.`ID` AS `typeid`,`t`.`idStyleUrl` AS `styleId`,`t`.`idSiteSize` AS `sizeId`,`t`.`idService` AS `serviceId`,`ss`.`description` AS `size`,`s`.`description` AS `service`,coalesce((select max(`rvpark`.`siterate`.`rate`) from `rvpark`.`siterate` where ((`t`.`ID` = `rvpark`.`siterate`.`idSiteType`) and (`rvpark`.`siterate`.`period` = 'Weekly'))),0) AS `week`,coalesce((select max(`rvpark`.`siterate`.`rate`) from `rvpark`.`siterate` where ((`t`.`ID` = `rvpark`.`siterate`.`idSiteType`) and (`rvpark`.`siterate`.`period` = 'Daily'))),0) AS `day` from ((`rvpark`.`sitetype` `t` join `rvpark`.`service` `s` on((`t`.`idService` = `s`.`ID`))) join `rvpark`.`sitesize` `ss` on((`t`.`idSiteSize` = `ss`.`ID`)));

CREATE ALGORITHM=UNDEFINED DEFINER=`conestoga`@`%` SQL SECURITY DEFINER VIEW `rvpark`.`staff_view` AS select `p`.`ID` AS `id`,`p`.`firstName` AS `firstName`,`p`.`lastName` AS `lastName`,concat(`p`.`firstName`,' ',`p`.`lastName`) AS `fullName`,`p`.`mainPhone` AS `mainPhone`,`p`.`email` AS `email`,`c`.`role` AS `role`,`p`.`password` AS `password` from (`rvpark`.`staff` `c` join `rvpark`.`person` `p` on((`c`.`ID` = `p`.`ID`)));
